// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: todo_ai.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AIConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          string                 `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`                                        // "local", "cloud", "hybrid"
	LocalEndpoint string                 `protobuf:"bytes,2,opt,name=local_endpoint,json=localEndpoint,proto3" json:"local_endpoint,omitempty"` // Ollama endpoint
	CloudEndpoint string                 `protobuf:"bytes,3,opt,name=cloud_endpoint,json=cloudEndpoint,proto3" json:"cloud_endpoint,omitempty"` // Cloud API endpoint
	ApiKey        string                 `protobuf:"bytes,4,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	ModelLocal    string                 `protobuf:"bytes,5,opt,name=model_local,json=modelLocal,proto3" json:"model_local,omitempty"`
	ModelCloud    string                 `protobuf:"bytes,6,opt,name=model_cloud,json=modelCloud,proto3" json:"model_cloud,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AIConfig) Reset() {
	*x = AIConfig{}
	mi := &file_todo_ai_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AIConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIConfig) ProtoMessage() {}

func (x *AIConfig) ProtoReflect() protoreflect.Message {
	mi := &file_todo_ai_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIConfig.ProtoReflect.Descriptor instead.
func (*AIConfig) Descriptor() ([]byte, []int) {
	return file_todo_ai_proto_rawDescGZIP(), []int{0}
}

func (x *AIConfig) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *AIConfig) GetLocalEndpoint() string {
	if x != nil {
		return x.LocalEndpoint
	}
	return ""
}

func (x *AIConfig) GetCloudEndpoint() string {
	if x != nil {
		return x.CloudEndpoint
	}
	return ""
}

func (x *AIConfig) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *AIConfig) GetModelLocal() string {
	if x != nil {
		return x.ModelLocal
	}
	return ""
}

func (x *AIConfig) GetModelCloud() string {
	if x != nil {
		return x.ModelCloud
	}
	return ""
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_todo_ai_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_todo_ai_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_todo_ai_proto_rawDescGZIP(), []int{1}
}

func (x *PingRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_todo_ai_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_todo_ai_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_todo_ai_proto_rawDescGZIP(), []int{2}
}

func (x *PingResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type SplitTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Config        *AIConfig              `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SplitTaskRequest) Reset() {
	*x = SplitTaskRequest{}
	mi := &file_todo_ai_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SplitTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SplitTaskRequest) ProtoMessage() {}

func (x *SplitTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_todo_ai_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SplitTaskRequest.ProtoReflect.Descriptor instead.
func (*SplitTaskRequest) Descriptor() ([]byte, []int) {
	return file_todo_ai_proto_rawDescGZIP(), []int{3}
}

func (x *SplitTaskRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SplitTaskRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SplitTaskRequest) GetConfig() *AIConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type SubTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Completed     bool                   `protobuf:"varint,2,opt,name=completed,proto3" json:"completed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubTask) Reset() {
	*x = SubTask{}
	mi := &file_todo_ai_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubTask) ProtoMessage() {}

func (x *SubTask) ProtoReflect() protoreflect.Message {
	mi := &file_todo_ai_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubTask.ProtoReflect.Descriptor instead.
func (*SubTask) Descriptor() ([]byte, []int) {
	return file_todo_ai_proto_rawDescGZIP(), []int{4}
}

func (x *SubTask) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SubTask) GetCompleted() bool {
	if x != nil {
		return x.Completed
	}
	return false
}

type SplitTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Priority      string                 `protobuf:"bytes,3,opt,name=priority,proto3" json:"priority,omitempty"`
	EstimatedTime string                 `protobuf:"bytes,4,opt,name=estimated_time,json=estimatedTime,proto3" json:"estimated_time,omitempty"`
	SubTasks      []*SubTask             `protobuf:"bytes,5,rep,name=sub_tasks,json=subTasks,proto3" json:"sub_tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SplitTaskResponse) Reset() {
	*x = SplitTaskResponse{}
	mi := &file_todo_ai_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SplitTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SplitTaskResponse) ProtoMessage() {}

func (x *SplitTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_todo_ai_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SplitTaskResponse.ProtoReflect.Descriptor instead.
func (*SplitTaskResponse) Descriptor() ([]byte, []int) {
	return file_todo_ai_proto_rawDescGZIP(), []int{5}
}

func (x *SplitTaskResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SplitTaskResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SplitTaskResponse) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *SplitTaskResponse) GetEstimatedTime() string {
	if x != nil {
		return x.EstimatedTime
	}
	return ""
}

func (x *SplitTaskResponse) GetSubTasks() []*SubTask {
	if x != nil {
		return x.SubTasks
	}
	return nil
}

type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"` // "user" or "assistant"
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_todo_ai_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_todo_ai_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_todo_ai_proto_rawDescGZIP(), []int{6}
}

func (x *ChatMessage) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type ChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	History       []*ChatMessage         `protobuf:"bytes,2,rep,name=history,proto3" json:"history,omitempty"`
	Config        *AIConfig              `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_todo_ai_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_todo_ai_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_todo_ai_proto_rawDescGZIP(), []int{7}
}

func (x *ChatRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ChatRequest) GetHistory() []*ChatMessage {
	if x != nil {
		return x.History
	}
	return nil
}

func (x *ChatRequest) GetConfig() *AIConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type ChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      string                 `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatResponse) Reset() {
	*x = ChatResponse{}
	mi := &file_todo_ai_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatResponse) ProtoMessage() {}

func (x *ChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_todo_ai_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatResponse.ProtoReflect.Descriptor instead.
func (*ChatResponse) Descriptor() ([]byte, []int) {
	return file_todo_ai_proto_rawDescGZIP(), []int{8}
}

func (x *ChatResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

type RAGQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	DocContent    string                 `protobuf:"bytes,2,opt,name=doc_content,json=docContent,proto3" json:"doc_content,omitempty"`
	Config        *AIConfig              `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RAGQueryRequest) Reset() {
	*x = RAGQueryRequest{}
	mi := &file_todo_ai_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RAGQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RAGQueryRequest) ProtoMessage() {}

func (x *RAGQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_todo_ai_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RAGQueryRequest.ProtoReflect.Descriptor instead.
func (*RAGQueryRequest) Descriptor() ([]byte, []int) {
	return file_todo_ai_proto_rawDescGZIP(), []int{9}
}

func (x *RAGQueryRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *RAGQueryRequest) GetDocContent() string {
	if x != nil {
		return x.DocContent
	}
	return ""
}

func (x *RAGQueryRequest) GetConfig() *AIConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type RAGQueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Answer        string                 `protobuf:"bytes,2,opt,name=answer,proto3" json:"answer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RAGQueryResponse) Reset() {
	*x = RAGQueryResponse{}
	mi := &file_todo_ai_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RAGQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RAGQueryResponse) ProtoMessage() {}

func (x *RAGQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_todo_ai_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RAGQueryResponse.ProtoReflect.Descriptor instead.
func (*RAGQueryResponse) Descriptor() ([]byte, []int) {
	return file_todo_ai_proto_rawDescGZIP(), []int{10}
}

func (x *RAGQueryResponse) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

var File_todo_ai_proto protoreflect.FileDescriptor

const file_todo_ai_proto_rawDesc = "" +
	"\n" +
	"\rtodo_ai.proto\x12\x02pb\"\xc7\x01\n" +
	"\bAIConfig\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\tR\x04mode\x12%\n" +
	"\x0elocal_endpoint\x18\x02 \x01(\tR\rlocalEndpoint\x12%\n" +
	"\x0ecloud_endpoint\x18\x03 \x01(\tR\rcloudEndpoint\x12\x17\n" +
	"\aapi_key\x18\x04 \x01(\tR\x06apiKey\x12\x1f\n" +
	"\vmodel_local\x18\x05 \x01(\tR\n" +
	"modelLocal\x12\x1f\n" +
	"\vmodel_cloud\x18\x06 \x01(\tR\n" +
	"modelCloud\"#\n" +
	"\vPingRequest\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"$\n" +
	"\fPingResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"p\n" +
	"\x10SplitTaskRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12$\n" +
	"\x06config\x18\x03 \x01(\v2\f.pb.AIConfigR\x06config\"=\n" +
	"\aSubTask\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x1c\n" +
	"\tcompleted\x18\x02 \x01(\bR\tcompleted\"\xb8\x01\n" +
	"\x11SplitTaskResponse\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\tR\bpriority\x12%\n" +
	"\x0eestimated_time\x18\x04 \x01(\tR\restimatedTime\x12(\n" +
	"\tsub_tasks\x18\x05 \x03(\v2\v.pb.SubTaskR\bsubTasks\";\n" +
	"\vChatMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"x\n" +
	"\vChatRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12)\n" +
	"\ahistory\x18\x02 \x03(\v2\x0f.pb.ChatMessageR\ahistory\x12$\n" +
	"\x06config\x18\x03 \x01(\v2\f.pb.AIConfigR\x06config\"*\n" +
	"\fChatResponse\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\tR\bresponse\"n\n" +
	"\x0fRAGQueryRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x1f\n" +
	"\vdoc_content\x18\x02 \x01(\tR\n" +
	"docContent\x12$\n" +
	"\x06config\x18\x03 \x01(\v2\f.pb.AIConfigR\x06config\"*\n" +
	"\x10RAGQueryResponse\x12\x16\n" +
	"\x06answer\x18\x02 \x01(\tR\x06answer2\xd2\x01\n" +
	"\tAIService\x12)\n" +
	"\x04Ping\x12\x0f.pb.PingRequest\x1a\x10.pb.PingResponse\x128\n" +
	"\tSplitTask\x12\x14.pb.SplitTaskRequest\x1a\x15.pb.SplitTaskResponse\x12)\n" +
	"\x04Chat\x12\x0f.pb.ChatRequest\x1a\x10.pb.ChatResponse\x125\n" +
	"\bRAGQuery\x12\x13.pb.RAGQueryRequest\x1a\x14.pb.RAGQueryResponseB1Z/github.com/Coke0807/AI-SmartTodo/backend/pkg/pbb\x06proto3"

var (
	file_todo_ai_proto_rawDescOnce sync.Once
	file_todo_ai_proto_rawDescData []byte
)

func file_todo_ai_proto_rawDescGZIP() []byte {
	file_todo_ai_proto_rawDescOnce.Do(func() {
		file_todo_ai_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_todo_ai_proto_rawDesc), len(file_todo_ai_proto_rawDesc)))
	})
	return file_todo_ai_proto_rawDescData
}

var file_todo_ai_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_todo_ai_proto_goTypes = []any{
	(*AIConfig)(nil),          // 0: pb.AIConfig
	(*PingRequest)(nil),       // 1: pb.PingRequest
	(*PingResponse)(nil),      // 2: pb.PingResponse
	(*SplitTaskRequest)(nil),  // 3: pb.SplitTaskRequest
	(*SubTask)(nil),           // 4: pb.SubTask
	(*SplitTaskResponse)(nil), // 5: pb.SplitTaskResponse
	(*ChatMessage)(nil),       // 6: pb.ChatMessage
	(*ChatRequest)(nil),       // 7: pb.ChatRequest
	(*ChatResponse)(nil),      // 8: pb.ChatResponse
	(*RAGQueryRequest)(nil),   // 9: pb.RAGQueryRequest
	(*RAGQueryResponse)(nil),  // 10: pb.RAGQueryResponse
}
var file_todo_ai_proto_depIdxs = []int32{
	0,  // 0: pb.SplitTaskRequest.config:type_name -> pb.AIConfig
	4,  // 1: pb.SplitTaskResponse.sub_tasks:type_name -> pb.SubTask
	6,  // 2: pb.ChatRequest.history:type_name -> pb.ChatMessage
	0,  // 3: pb.ChatRequest.config:type_name -> pb.AIConfig
	0,  // 4: pb.RAGQueryRequest.config:type_name -> pb.AIConfig
	1,  // 5: pb.AIService.Ping:input_type -> pb.PingRequest
	3,  // 6: pb.AIService.SplitTask:input_type -> pb.SplitTaskRequest
	7,  // 7: pb.AIService.Chat:input_type -> pb.ChatRequest
	9,  // 8: pb.AIService.RAGQuery:input_type -> pb.RAGQueryRequest
	2,  // 9: pb.AIService.Ping:output_type -> pb.PingResponse
	5,  // 10: pb.AIService.SplitTask:output_type -> pb.SplitTaskResponse
	8,  // 11: pb.AIService.Chat:output_type -> pb.ChatResponse
	10, // 12: pb.AIService.RAGQuery:output_type -> pb.RAGQueryResponse
	9,  // [9:13] is the sub-list for method output_type
	5,  // [5:9] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_todo_ai_proto_init() }
func file_todo_ai_proto_init() {
	if File_todo_ai_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_todo_ai_proto_rawDesc), len(file_todo_ai_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_todo_ai_proto_goTypes,
		DependencyIndexes: file_todo_ai_proto_depIdxs,
		MessageInfos:      file_todo_ai_proto_msgTypes,
	}.Build()
	File_todo_ai_proto = out.File
	file_todo_ai_proto_goTypes = nil
	file_todo_ai_proto_depIdxs = nil
}
