# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import todo_ai_pb2 as todo__ai__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in todo_ai_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AIServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/pb.AIService/Ping',
                request_serializer=todo__ai__pb2.PingRequest.SerializeToString,
                response_deserializer=todo__ai__pb2.PingResponse.FromString,
                _registered_method=True)
        self.SplitTask = channel.unary_unary(
                '/pb.AIService/SplitTask',
                request_serializer=todo__ai__pb2.SplitTaskRequest.SerializeToString,
                response_deserializer=todo__ai__pb2.SplitTaskResponse.FromString,
                _registered_method=True)
        self.Chat = channel.unary_unary(
                '/pb.AIService/Chat',
                request_serializer=todo__ai__pb2.ChatRequest.SerializeToString,
                response_deserializer=todo__ai__pb2.ChatResponse.FromString,
                _registered_method=True)
        self.RAGQuery = channel.unary_unary(
                '/pb.AIService/RAGQuery',
                request_serializer=todo__ai__pb2.RAGQueryRequest.SerializeToString,
                response_deserializer=todo__ai__pb2.RAGQueryResponse.FromString,
                _registered_method=True)


class AIServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Ping(self, request, context):
        """基础连通性测试
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SplitTask(self, request, context):
        """智能任务拆解与评估
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Chat(self, request, context):
        """全局 AI 助手对话 (云端大模型)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RAGQuery(self, request, context):
        """RAG 知识库问答 (本地轻量模型)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AIServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=todo__ai__pb2.PingRequest.FromString,
                    response_serializer=todo__ai__pb2.PingResponse.SerializeToString,
            ),
            'SplitTask': grpc.unary_unary_rpc_method_handler(
                    servicer.SplitTask,
                    request_deserializer=todo__ai__pb2.SplitTaskRequest.FromString,
                    response_serializer=todo__ai__pb2.SplitTaskResponse.SerializeToString,
            ),
            'Chat': grpc.unary_unary_rpc_method_handler(
                    servicer.Chat,
                    request_deserializer=todo__ai__pb2.ChatRequest.FromString,
                    response_serializer=todo__ai__pb2.ChatResponse.SerializeToString,
            ),
            'RAGQuery': grpc.unary_unary_rpc_method_handler(
                    servicer.RAGQuery,
                    request_deserializer=todo__ai__pb2.RAGQueryRequest.FromString,
                    response_serializer=todo__ai__pb2.RAGQueryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pb.AIService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pb.AIService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AIService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.AIService/Ping',
            todo__ai__pb2.PingRequest.SerializeToString,
            todo__ai__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SplitTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.AIService/SplitTask',
            todo__ai__pb2.SplitTaskRequest.SerializeToString,
            todo__ai__pb2.SplitTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Chat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.AIService/Chat',
            todo__ai__pb2.ChatRequest.SerializeToString,
            todo__ai__pb2.ChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RAGQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.AIService/RAGQuery',
            todo__ai__pb2.RAGQueryRequest.SerializeToString,
            todo__ai__pb2.RAGQueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
