# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: todo_ai.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'todo_ai.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rtodo_ai.proto\x12\x02pb\"\x83\x01\n\x08\x41IConfig\x12\x0c\n\x04mode\x18\x01 \x01(\t\x12\x16\n\x0elocal_endpoint\x18\x02 \x01(\t\x12\x16\n\x0e\x63loud_endpoint\x18\x03 \x01(\t\x12\x0f\n\x07\x61pi_key\x18\x04 \x01(\t\x12\x13\n\x0bmodel_local\x18\x05 \x01(\t\x12\x13\n\x0bmodel_cloud\x18\x06 \x01(\t\"\x1c\n\x0bPingRequest\x12\r\n\x05value\x18\x01 \x01(\t\"\x1d\n\x0cPingResponse\x12\r\n\x05value\x18\x01 \x01(\t\"T\n\x10SplitTaskRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x1c\n\x06\x63onfig\x18\x03 \x01(\x0b\x32\x0c.pb.AIConfig\"+\n\x07SubTask\x12\r\n\x05title\x18\x01 \x01(\t\x12\x11\n\tcompleted\x18\x02 \x01(\x08\"\x81\x01\n\x11SplitTaskResponse\x12\r\n\x05title\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x10\n\x08priority\x18\x03 \x01(\t\x12\x16\n\x0e\x65stimated_time\x18\x04 \x01(\t\x12\x1e\n\tsub_tasks\x18\x05 \x03(\x0b\x32\x0b.pb.SubTask\",\n\x0b\x43hatMessage\x12\x0c\n\x04role\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"^\n\x0b\x43hatRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\x12 \n\x07history\x18\x02 \x03(\x0b\x32\x0f.pb.ChatMessage\x12\x1c\n\x06\x63onfig\x18\x03 \x01(\x0b\x32\x0c.pb.AIConfig\" \n\x0c\x43hatResponse\x12\x10\n\x08response\x18\x01 \x01(\t\"S\n\x0fRAGQueryRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\x13\n\x0b\x64oc_content\x18\x02 \x01(\t\x12\x1c\n\x06\x63onfig\x18\x03 \x01(\x0b\x32\x0c.pb.AIConfig\"\"\n\x10RAGQueryResponse\x12\x0e\n\x06\x61nswer\x18\x02 \x01(\t2\xd2\x01\n\tAIService\x12)\n\x04Ping\x12\x0f.pb.PingRequest\x1a\x10.pb.PingResponse\x12\x38\n\tSplitTask\x12\x14.pb.SplitTaskRequest\x1a\x15.pb.SplitTaskResponse\x12)\n\x04\x43hat\x12\x0f.pb.ChatRequest\x1a\x10.pb.ChatResponse\x12\x35\n\x08RAGQuery\x12\x13.pb.RAGQueryRequest\x1a\x14.pb.RAGQueryResponseB1Z/github.com/Coke0807/AI-SmartTodo/backend/pkg/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'todo_ai_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z/github.com/Coke0807/AI-SmartTodo/backend/pkg/pb'
  _globals['_AICONFIG']._serialized_start=22
  _globals['_AICONFIG']._serialized_end=153
  _globals['_PINGREQUEST']._serialized_start=155
  _globals['_PINGREQUEST']._serialized_end=183
  _globals['_PINGRESPONSE']._serialized_start=185
  _globals['_PINGRESPONSE']._serialized_end=214
  _globals['_SPLITTASKREQUEST']._serialized_start=216
  _globals['_SPLITTASKREQUEST']._serialized_end=300
  _globals['_SUBTASK']._serialized_start=302
  _globals['_SUBTASK']._serialized_end=345
  _globals['_SPLITTASKRESPONSE']._serialized_start=348
  _globals['_SPLITTASKRESPONSE']._serialized_end=477
  _globals['_CHATMESSAGE']._serialized_start=479
  _globals['_CHATMESSAGE']._serialized_end=523
  _globals['_CHATREQUEST']._serialized_start=525
  _globals['_CHATREQUEST']._serialized_end=619
  _globals['_CHATRESPONSE']._serialized_start=621
  _globals['_CHATRESPONSE']._serialized_end=653
  _globals['_RAGQUERYREQUEST']._serialized_start=655
  _globals['_RAGQUERYREQUEST']._serialized_end=738
  _globals['_RAGQUERYRESPONSE']._serialized_start=740
  _globals['_RAGQUERYRESPONSE']._serialized_end=774
  _globals['_AISERVICE']._serialized_start=777
  _globals['_AISERVICE']._serialized_end=987
# @@protoc_insertion_point(module_scope)
